version: "3.2"

services:
  db:
    image: 'postgres:latest'
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  api:
    image: 'untitledso/api:latest'
    ports: 
      - "4000:4000"
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: "./"
    depends_on: 
      - db
      - api
    ports:
      - "3000:3000"